---
name: test
on: # yamllint disable-line rule:truthy
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: alexellis/arkade-get@master
        with:
          flux: v2.3.0
          helm: latest
          kind: v0.24.0
          kubectl: v1.29.9
      - name: flux version
        run: flux version --client
      - name: helm version
        run: helm version --client
      - name: kind version
        run: kind version
      - name: kubectl version
        run: kubectl version --client
